---
abstract: 'Markdown-based slidedeck server app'
author:
  - 'Yanick Champoux <yanick@cpan.org>'
build_requires:
  Module::Build: 0.3601
  Test::More: 0.88
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300037, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Chorus
provides:
  App::Chorus:
    file: lib/App/Chorus.pm
    version: v0.2.1
requires:
  Cache::FastMmap: 0
  Dancer: 0
  Dancer::Plugin::Cache::CHI: 0
  Dancer::Plugin::WebSocket: 0
  Dancer::Template::Mason: 0
  File::ShareDir::Tarball: 0
  File::Slurp: 0
  Getopt::Long: 0
  HTML::Entities: 0
  Path::Tiny: 0
  Plack::Loader: 0
  Text::Markdown: 0
  perl: v5.10.0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=App-Chorus
  homepage: http://search.cpan.org/dist/App-Chorus/
  repository: https://github.com/yanick/chorus.git
version: 0.2.1
x_author_pledge:
  version: 1
x_authority: cpan:YANICK
x_contributors:
  - 'Drew Taylor <drew@drewtaylor.com>'
  - 'Yanick Champoux <yanick@babyl.dyndns.org>'
